#!/bin/sh

LOG=/var/log/dpkg-autoconfigure.log

# Perl is noisy if these are not set.
: ${LC_ALL:=C}; export LC_ALL
: ${LANG:=C}; export LANG
: ${LANGUAGE:=C}; export LANGUAGE

# Configure all pending packages after importing debconf selections.

cat /usr/share/dpkg-autoconfigure/selections.d/* 2>/dev/null \
| debconf-set-selections

# Potentially configure a few times to overcome cyclic dependencies.
export DEBIAN_FRONTEND=noninteractive
export DEBIAN_NONINTERACTIVE_SEEN=true
{
	dpkg --configure --pending ||
	dpkg --configure --pending ||
	dpkg --configure --pending ||
	dpkg --configure --pending ||
	dpkg --configure --pending
} 2>&1 | tee -a $LOG | grep '^Setting up '
gzip $LOG
